### ISSUE TITLE
solace_sink_properties.json contains passwords

### ISSUE THREAD

**Issue by TomFairbairnSolace** [SolaceProducts/pubsubplus-connector-kafka-sink#13]
Original code JSON:
                "sol.ssl_trust_store": "/opt/PKI/skeltonCA/heinz1.ts",
		"sol.ssl_trust_store_pasword": "sasquatch",
		"sol.ssl_trust_store_format": "JKS",
		"sol.ssl_key_store": "/opt/PKI/skeltonCA/heinz1.ks",
		"sol.ssl_key_store_password": "sasquatch",
		"sol.ssl_key_store_format": "JKS",
		"sol.ssl_key_store_normalized_format": "JKS",
		"sol.ssl_private_key_alias": "heinz1",
		"sol.ssl_private_key_password": "sasquatch",
I'm not sure of the correct style, but something like 
"sol.ssl_trust_store": "path/to/your/trust store"
would probably be better

**Comment by bczoma** [comment]
I have reorganized this and removed passwords as part of the productization updates.
