### ISSUE TITLE
Bug: SolaceSinkTask should not called the stop method when Solace transaction failed to be commited.

### ISSUE THREAD

**Issue by fhussonnois** [SolaceProducts/pubsubplus-connector-kafka-sink#30]
**Description of the bug**

If `SolaceSinkConstants.SOl_USE_TRANSACTIONS_FOR_QUEUE` is configured to `true` and a `JCSMPException` is thrown while a solace transaction is committed then the `SolaceSinkTask#stop` method is called internally by the `SolaceSinkTask` itself. Therefore, the task is still considered to be RUNING and the `put` method will continue to be called by Kafka Connect.

In a way this issue is similitar to #29 

https://github.com/SolaceProducts/pubsubplus-connector-kafka-sink/blob/29abade80dd0d359b8e51b43bd6b1a584d2abb62/src/main/java/com/solace/connector/kafka/connect/sink/SolaceSinkTask.java#L123-L137

**Expected behavior**

An exception should be thrown (i.e., `ConnectException`) so that Kafka Connect will invoke the `stop` method and put the task in failed status.

**Comment by Nephery** [comment]
While #40 does technically fix this issue, from my testing and looking at the [`WorkerSinkTask` source code](https://github.com/apache/kafka/blob/2.8.0/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L392-L401), the `WorkerSinkTask` seems to disregard any `errors.*` configuration set on the sink connector for errors thrown from `SinkTask.put()` and `SinkTask.preCommit()` (and `SinkTask.flush()` in turn).

Instead, this is what it does for both operations:

* `SinkTask.put()`: [`RetriableException`s thrown from this function will cause the worker to retry forever.](https://github.com/apache/kafka/blob/2.8.0/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L599-L605)
* `SinkTask.preCommit()`: [**Any exceptions** thrown from this function will cause the worker to retry forever.](https://github.com/apache/kafka/blob/2.8.0/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L392-L401)
