### ISSUE TITLE
Feat request: pubsubplus-connector-kafka-sink should be available on Maven Central

### ISSUE THREAD

**Issue by fhussonnois** [SolaceProducts/pubsubplus-connector-kafka-sink#31]
**Feature request**

Most of the time, pubsubplus-connector-kafka-sink involves the implementation of custom classes, for example, SolRecordProcessorIF. For this reason, it would be convenient for the connector API to be available on a maven repository so that custom classes can be packaged independently of the connnector.

**Comment by Nephery** [comment]
2.2.0 was uploaded to Maven Central.

See https://github.com/SolaceProducts/pubsubplus-connector-kafka-sink#build-a-new-record-processor for more info.
