### ISSUE TITLE
Feat request: Message DeliveryMode should be configurable

### ISSUE THREAD

**Issue by fhussonnois** [SolaceProducts/pubsubplus-connector-kafka-sink#34]
**Feature request**

Currrently, the `DeliveryMode` used for sending messages to a solace queue or topic is hard-coded (i.e., either `DeliveryMode.PERSISTENT` for queue and `DeliveryMode.DIRECT` for topic).

It would be more convenient to be able to pass the delivery-mode to use throught the connector's configuration. 

**Proposed Changes** 

The connector should support a new property `sink.solace.delivery.mode` to dynamically configure the delivery-mode to be used by the `SolaceSinkSender`.

**Comment by Nephery** [comment]
#44 Adds transaction support for publishing persistent messages to topics by setting `sol.use_transactions_for_topics=true`.
