### ISSUE TITLE
Kafka Connect (confluent) has a wrong descriptions for the topic & queue settings

### ISSUE THREAD

**Issue by dev-mansonthomas** [SolaceProducts/pubsubplus-connector-kafka-sink#47]
Since the Sink connector is fetching record from Kafka and pushing it to solace.

Shouldn't the topic and queue description be : 
topic to push to (instead of Subscribe from)
Queue to push to (instead of Consume from) ?

![image](https://user-images.githubusercontent.com/5695269/150156611-723bd977-cc56-4145-bafe-66ab87d665ad.png)
![image](https://user-images.githubusercontent.com/5695269/150156678-8577907d-e001-4380-a5a6-fabad50b0a1c.png)

**Comment by bczoma** [comment]
Addressed in v2.3.0, fixed
